@startuml

component Server {
    component Rest {
        package no.ntnu.cardsnap.rest
        package no.ntnu.cardsnap.rest.services
        package no.ntnu.cardsnap.rest.repositories
        package no.ntnu.cardsnap.rest.controllers
    }
    component Core {
        package no.ntnu.cardsnap.core
    }
    component Persistence {
        package no.ntnu.cardsnap.persistence
    }
}

component Client {
    component WebApp
}

component SpringBoot
component SpringDoc
component SwaggerAnnotations
component GoogleGson
component React
component ReactQuery
component ReactRouterDOM
component Axios

WebApp ..> Server
WebApp ..> React
WebApp ..> ReactQuery
WebApp ..> ReactRouterDOM
WebApp ..> Axios
Persistence ..> GoogleGson
Core ..> Persistence
Rest ..> Persistence
Rest ..> Core
Rest ..> SpringBoot
Rest ..> SpringDoc
Rest ..> SwaggerAnnotations

@enduml
