@startuml

component no.ntnu.cardsnap.types
component no.ntnu.cardsnap.core
component no.ntnu.cardsnap.persistence

component RESTServer {
    package no.ntnu.cardsnap.rest
}

component WebClient {
    component "React App"
}

component FXClient {
    package no.ntnu.cardsnap.fx
}

component deps.SpringBoot
component deps.SpringDoc
component deps.SwaggerAnnotations
component deps.GoogleGson
component deps.JavaFX
component deps.React
component deps.ReactQuery
component deps.ReactRouterDOM
component deps.Axios

no.ntnu.cardsnap.core ..> no.ntnu.cardsnap.persistence
no.ntnu.cardsnap.core ..> no.ntnu.cardsnap.types

no.ntnu.cardsnap.persistence ..> no.ntnu.cardsnap.types
no.ntnu.cardsnap.persistence ..> deps.GoogleGson

RESTServer ..> no.ntnu.cardsnap.core
RESTServer ..> no.ntnu.cardsnap.persistence
RESTServer ..> no.ntnu.cardsnap.types
RESTServer ..> deps.SpringBoot
RESTServer ..> deps.SpringDoc
RESTServer ..> deps.SwaggerAnnotations

FXClient ..> no.ntnu.cardsnap.core
FXClient ..> no.ntnu.cardsnap.persistence
FXClient ..> no.ntnu.cardsnap.types
FXClient ..> deps.JavaFX

WebClient ..> RESTServer
WebClient ..> deps.React
WebClient ..> deps.ReactRouterDOM
WebClient ..> deps.Axios
WebClient ..> deps.ReactQuery

@enduml
